controller_list:
  - name: fake_kuka_arm_controller
    joints:
      - base_to_link1
      - link1_to_link2
      - link2_to_link3
      - link3_to_link4
      - link4_to_link5
      - link5_to_link6